// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus";

const application = Application.start();

// Configure Stimulus development experience
application.debug = false;
window.Stimulus = application;

import MapController from "./map_controller";
application.register("map", MapController);

import ForecastController from "./forecast_controller";
application.register("forecast", ForecastController);

import NavigationController from "./navigation_controller";
application.register("navigation", NavigationController);

import ShareController from "./share_controller";
application.register("share", ShareController);
