// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import MapController from "./map_controller";
application.register("map", MapController);

import PredictionController from "./prediction_controller";
application.register("prediction", PredictionController);

import TabController from "./tab_controller";
application.register("tab", TabController);
